# Generated by Django 2.0.5 on 2018-05-02 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = [
    ]
