# Generated by Django 2.0.5 on 2018-05-07 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimap_base', '0002_second'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'verbose_name_plural': 'campuses'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name_plural': 'universities'},
        ),
        migrations.AlterField(
            model_name='campus',
            name='group',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='university',
            name='slug',
            field=models.SlugField(max_length=32),
        ),
    ]
